Provide label through smartapi yaml
biothings/api-respone-transform.js pull request #44
Opened 2022-12-22 02:52 UTC by rjawesome

For https://github.com/biothings/BioThings_Explorer_TRAPI/issues/539

2023-01-04 18:17 UTC, tokebe requested changes
The implementation currently doesn't freeze/unfreeze properly, meaning the label could be lost in record caching. See inline comments. Additionally, the label property needs to be correctly added to the `RecordNode.toJSON()` and `RecordNode.freezeMinimal()` methods.

2023-01-04 18:17 UTC, tokebe commented on src/transformers/transformer.ts
> +            return new Record(copyRecord, { ...this.config, subject_name: subjectName, object_name: objectName }, this.edge.association, this.edge.reasoner_edge);
Instead of attaching the subject and object to the config, you could change the frozenRecord construction to attach the subject and object names inside the record subject and object, e.g.:

```javascript
const frozenRecord = {
  subject: {...this._getSubject(subjectCurie), label: subjectName},
  ... // rest of the object
}
```

2023-01-04 18:17 UTC, tokebe commented on src/record.ts
> +  constructor(node: FrozenNode | VerboseFrozenNode | MinimalFrozenNode, qNode: QNode, label: string) {
`label` should be a property on `node` so it can freeze/unfreeze properly.

2023-01-04 18:18 UTC, tokebe commented on src/transformers/transformer.ts
> +            return new Record(copyRecord, { ...this.config, subject_name: subjectName, object_name: objectName }, this.edge.association, this.edge.reasoner_edge);
The same can be done when creating `copyRecord`'s object.

2023-01-05 20:07 UTC, tokebe commented
Currently fails tests due to tests not defining an apiLabel in the test. This is probably best remedied by making apiLabel optional in RecordNode.

2023-01-06 01:25 UTC, rjawesome commented
Fixed

2023-02-08 18:39 UTC, tokebe approved these changes

2023-02-24 05:56 UTC, colleenXu commented
I tested this PR with the linked SmartAPI yaml changes above, and I think it works. `input_name` and `output_name` are the x-bte response-mapping keys to use. 

I don't think it's urgent to get these onto prod/test instances, since I tested how BTE behaves with the SmartAPI yaml changes + without this PR, and it behaves okay (input_name / output_name become normal edge-attributes). 

Notes:
* I sometimes notice that the mapped field may correspond to multiple strings (an array of strings?) rather than just a string. In these situations, the code seems to handle these okay (it seems to pick the first string option). But I want to note this in case we encounter buggy behavior later
* the nodes also have a node-attribute "biolink:synonym", and that isn't mutated to use the label from the mapped fields. VS for SRI Node Normalizer, when we retrieve labels/names we put them in that node-attribute as well. 
    * Andrew said it's okay to leave this behavior since it's minor and the node-attribute isn't really used right now

2023-02-24 06:20 UTC, colleenXu commented
@tokebe I think this is ready for next steps (the notes section of my post above might be relevant)

2023-03-09 19:15 UTC, merged